title: Netty
base_url: http://netty.io/

google_analytics: UA-95307-5
disqus: netty0

releases:
  - version: 4.0.0.CR2
    date: 08-May-2013
    stable: false
  - version: 3.6.5.Final
    date: 09-Apr-2013
    stable: true

twitter_search_url: 'https://twitter.com/search?q=%40netty_project%20OR%20%23nettyio%20OR%20%23netty%20-TeenImagines%20-netty_bot%20-%23pot%20-%23imagine%20-instagr.am'

