title: Netty
base_url: http://netty.io/

google_analytics: UA-95307-5
disqus: netty0

releases:
  - version: 4.0.0.Beta1
    date: 14-Feb-2013
    stable: false
  - version: 3.6.2.Final
    date: 16-Jan-2013
    stable: true

