title: Netty
base_url: http://netty.io/

google_analytics: UA-95307-5
disqus: netty0

releases:
  - version: 5.0.0.Alpha1
    date: 22-Dec-2013
    stable: false
    branch: master
  - version: 4.1.0.Beta1
    date: 04-Jul-2014
    stable: false
  - version: 4.0.21.Final
    date: 01-Jul-2014
    stable: true
  - version: 3.9.2.Final
    date: 11-Jun-2014
    stable: true

twitter_search_url: 'https://twitter.com/search?q=%40netty_project OR %23netty lang%3Aen'

default_sidebar: '<div id="twitter-timeline" class="hidden-xs hidden-sm hidden-print" role="complementary"><a class="twitter-timeline" href="https://twitter.com/netty_project" data-widget-id="412058459593383936">Tweets by @netty_project</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></div>'

shortened_links:
  icla: 'https://docs.google.com/spreadsheet/viewform?formkey=dHBjc1YzdWhsZERUQnhlSklsbG1KT1E6MQ'
  ccla: 'https://docs.google.com/spreadsheet/viewform?formkey=dG9wTmhoeGNGd1MtdFdtVXl4TlVSNlE6MQ'

